name: test

on:
  push:
  pull_request:

jobs:
  test-matrix:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Install Go deps
        run: |
          go get github.com/golangci/govet
          go get golang.org/x/lint/golint

      - name: Lint and Test
        run: |
          test -z $(go fmt ./...)
          go vet ./...
          golint ./...
          go test ./...
